#!/bin/sh
readonly ID_PREVIEW="preview"
export FIFO_UEBERZUG="/tmp/lf-ueberzug-${PPID}"



main() {
  case "$1" in
    "clear")
      printf "action\tremove\tidentifier\t%s\n" "$ID_PREVIEW" > "$FIFO_UEBERZUG"
      ;;
    "draw")
      printf "action\tadd\tidentifier\t%s\tx\t%s\ty\t%s\tmax_width\t%s\tmax_height\t%s\tpath\t%s\n" "$ID_PREVIEW" "$3" "$4" "$5" "$6" "$2" > "$FIFO_UEBERZUG"
      ;;
    "*") echo "Unknown command: '$1', '$2'" ;;
  esac
}

# shellcheck disable=SC2068
main $@