#! /bin/sh
export AWT_TOOLKIT=MToolkit
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc rule -a Slack desktop='^1'
bspc rule -a St desktop='^2'
bspc rule -a Kitty desktop='^2'
bspc rule -a Chromium desktop='^3'

source ~/.fehbg &
clight &
picom &
dex bspwm -ae bspwm &
~/.config/polybar/launch.sh &
$(sleep 2 && st) &
chromium &
slack &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

$(sleep 2 && bspc desktop -f '^2') &
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc rule -a Gimp desktop='^8' state=floating follow=on