#!/bin/bash
export AWT_TOOLKIT=MToolkit
bspc config external_rules_command /home/alan/bin/bspwm_external_rules
sxhkd &

# MONITOR_NAMES=( $(bspc query -M --names) )

if [[ $(hostname) != "ajenkins-synalogik" ]]; then
  bspc monitor HDMI-A-0 -d 1 4
  bspc monitor DisplayPort-2 -d 2 3 9 0
fi

# bspc rule -a Slack desktop='1'
# bspc rule -a St desktop='2'
# bspc rule -a Kitty desktop='2'
# bspc rule -a Chromium desktop='3'
# bspc rule -a firefox desktop='3'
# bspc rule -a 'Microsoft Teams - Preview' desktop='4'
# bspc rule -a Steam desktop='9' floating=on
# bspc rule -a 'steam_app_*' desktop='0'

source ~/.fehbg &
# clight &
picom &
dex bspwm -ae bspwm &
# steam -silent &
~/.config/polybar/launch.sh &
/home/alan/bin/start-preferred-terminal --tmux &
# slack &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# prevent focus stealing
bspc config ignore_ewmh_focus true
