#! /bin/sh
sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

source ~/.fehbg &
picom &
dex bspwm -ae bspwm &
~/.config/polybar/launch.sh &
st &
chromium &
slack &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a slack desktop='^1'
bspc rule -a st desktop='^2'
bspc rule -a kitty desktop='^2'
bspc rule -a Chromium desktop='^3'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc rule -a Gimp desktop='^8' state=floating follow=on