#!/usr/bin/env bash
shopt -s nullglob globstar

private_mode=0

if [[ $1 == "--private-mode" ]]; then
  private_mode=1
  shift
fi

export AWS_DEFAULT_REGION=eu-west-1

aws_profiles=( $(grep '\[profile ' ~/.aws/config | sed -e 's/\[profile //' -e 's/\]//') )

profile=$(printf '%s\n' "${aws_profiles[@]}" | rofi -dmenu "$@")

[[ -n $profile ]] || exit

if [[ $private_mode -eq 0 ]]; then
  INCOGNITO=""
else
  INCOGNITO="--incognito"
fi
export AWS_MFA_ZENITY="true"

if command -v "awsconsole" &>/dev/null; then
  URL=$(awsconsole -u "$profile")
else
  URL=$(assume-role -console "$profile")
fi

xdg-open "$URL"