-- General configuration
require('settings')
require('neovide-settings')
require('nv-utils')
require('nv-autocommands')
require('keymappings')

--vim.cmd('source ~/.config/nvim/vimscript/functions.vim')

-- Plugin configs
require('lsp-trouble')
require('nv-bookmark')
require('nv-colorizer')
require('nv-comment')
require('nv-compe')
require('nv-dial')
require('nv-emmet')
require('nv-firenvim')
require('nv-floaterm')
require('nv-galaxyline')
require('nv-gitblame')
require('nv-gitsigns')
require('nv-hop')
require('nv-indentline')
require('nv-lightbulb')
require('nv-lspinstall')
require('nv-lspkind')
require('nv-matchup')
require('nv-nvimtree')
require('nv-quickscope')
require('nv-startify')
require('nv-telescope')
require('nv-terraform-completion')
require('nv-vim-rooter')
require('nv-vimspector')
require('tokyonight')
require('vim-terraform')
require('whichkey')

-- Load plugins
require('plugins')
